# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    

jobs:
  frontend:
      runs-on: self-hosted
      run:
        working-directory: ./issue-tracker
      strategy:
        matrix:
          node-version: [12.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

  backend:
      runs-on: self-hosted    
      run:
         working-directory: ./issue-server
      strategy:
        matrix:
          node-version: [12.x]

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          DB_PROD_URL = ${{ secrets.DB_PROD_URL }}
          SECRET = ${{ secrets.SECRET }}
          DB_DEV_URL = ${{ secrets.DB_DEV_URL }}
          DB_TEST_URL = ${{ secrets.DB_TEST_URL }}
          db = ${{ secrets.db }}
          CLOUD_NAME = ${{ secrets.CLOUD_NAME }}
          API_KEY = ${{ secrets.API_KEY }}
          API_SECRET = ${{ secrets.API_SECRET }}
          CLOUDINARY = ${{ secrets.CLOUDINARY }}
      - run: npm i
      - run: npm run build --if-present
      - run: npm test
      - run: pm2 restart Apollo

